name: Moonshot

on:
  workflow_dispatch:
    
jobs:
  container:
    runs-on: [ubuntu-latest]
    steps:    
    - uses: actions/checkout@v2
    - name: Docker Build
      shell: bash
      run: |
        docker build . -t ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Publish
      shell: bash
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
